name: udgam2k23
description: The UDGAM app - your go-to guide for our college's cultural fest!
  Get schedules and real-time updates on events and performances. Register and
  buy tickets through the app, and create a personalized schedule. Connect with
  other attendees and share your experiences. Available for iOS and Android, and
  accessible to all.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  easy_image_viewer: ^1.2.0
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  insta_image_viewer: ^1.0.2
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  fonts:
    - family: Samarkan
      fonts:
        - asset: assets/fonts/SAMARKAN.TTF
  assets:
    - assets/carousel/
    - assets/gallery/
    - assets/auth/
    - assets/images/
    - assets/featured_events/
    - assets/teams/CoreTeam/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
